// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRCRF6tnxERM8VmlO70gmwKZA99_64oY',
    appId: '1:259621204399:android:db71f8bb990cfd7c70bf5a',
    messagingSenderId: '259621204399',
    projectId: 'demoapp-41b06',
    storageBucket: 'demoapp-41b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1S1mUR8vVtHs1gBb6CCThMq9N3vOaCG8',
    appId: '1:259621204399:ios:f114226fdbf780ea70bf5a',
    messagingSenderId: '259621204399',
    projectId: 'demoapp-41b06',
    storageBucket: 'demoapp-41b06.appspot.com',
    androidClientId: '259621204399-e0k39uar0kflhq08dgqaptcn3g763kap.apps.googleusercontent.com',
    iosClientId: '259621204399-sho7eb50t56h1ntfconlq22bcj9s0eho.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialgooglesignin',
  );
}
